% Parameters
INPUT_FILE= "./media/news.qcif";
OUTPUT_FILE = "test.meh";

WIDTH = 176;
HEIGHT = 144;

% DCT
BLOCK_SIZE = 8;

% QUANTIZATION
N = 18;

% Constants
NB_FRAME = 1;%dir(INPUT_FILE).bytes/(WIDTH*HEIGHT + WIDTH*HEIGHT/2);
BITSTREAM_WIDTH = BLOCK_SIZE^2;
BITSTREAM_HEIGHT = WIDTH*HEIGHT/BLOCK_SIZE^2;